version: "3.7"

services:
    nodejs:
        container_name: ${PROJECT_NAME}_nodejs_${ENVIRONMENT}
        image: "node:12" 
        working_dir: /home/node/app
        environment:
            NODE_ENV: ${ENVIRONMENT}
            DB_NAME: MyFAS
            DB_LOGIN: postgres
            DB_PASSWORD: postgres
        volumes:
            - ./:/home/node/app
        command: >
            bash -c "npm install &&
                     npm run start:${ENVIRONMENT}"
        ports: 
            - "${PORT}:3000"
            - "${DEBUG_PORT}:9229"
        depends_on:
            - "postgres"

    postgres:
        container_name: ${PROJECT_NAME}_postgres_${ENVIRONMENT}
        image: postgres:12
        environment:
            POSTGRES_DB: MyFAS
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA: /var/lib/postgresql/data
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data    