version: "3.7"
services:
    app:
      build: .
      image: ${DOCKER_IMAGE_NAME}
      container_name: ${PROJECT_NAME}_nodejs_${NODE_ENV}
      entrypoint: ["npm","run","${NODE_ENV}"]
      depends_on:
        - postgres
      ports:
        - "3000:3000"
        - "9229:9229"
      env_file: 
        - .env
      volumes:
        - ./:/home/app
  
    postgres:
      container_name: ${PROJECT_NAME}_postgres_${NODE_ENV}
      image: postgres:12-alpine
      hostname: ${DB_HOST}
      environment:
        POSTGRES_DB: ${DB_NAME}
        PGPORT: ${DB_PORT}
        PGDATA: "/var/lib/postgresql/data"
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}