version: "3.7"
services:
    nodejs:
      image: node:12
      container_name: ${PROJECT_NAME}_nodejs_${NODE_ENV}
      working_dir: /home/app
      volumes:
        - ./:/home/app
      env_file: 
        - .env
      command: >
        bash -c "npm install && 
                npm run ${NODE_ENV}"
      depends_on:
        - postgres
      ports:
        - "${PORT}:3000"
        - "${DEBUG_PORT}:9229"

    postgres:
      container_name: ${PROJECT_NAME}_postgres_${NODE_ENV}
      image: postgres:12
      hostname: ${DB_HOST}
      environment:
        POSTGRES_DB: ${DB_NAME}
        PGPORT: ${DB_PORT}
        PGDATA: "/var/lib/postgresql/data"
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
