version: "3.7"

services:
    nodejs:
        container_name: ${PROJECT_NAME}_nodejs
        image: "node:12" 
        working_dir: /home/node/app
        environment:
          - NODE_ENV=${ENVIRONMENT}
        volumes:
            - ./:/home/node/app
        command: >
            bash -c "npm install &&
                     npm run start:${ENVIRONMENT}"
        ports: 
            - "${PORT}:3000"
            - "${DEBUG_PORT}:9229"
        depends_on:
            - "postgres"

    postgres:
        container_name: ${PROJECT_NAME}_postgres
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
            POSTGRES_USER: ${DB_ROOT_LOGIN}
            POSTGRES_DB: ${DB_NAME}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./pgdata:/var/lib/postgresql/data    