version: "3.7"
services:
    app:
      build: .
      # image: myfas-api:dev
      container_name: myfas-api-nodejs
      working_dir: /home/app
      volumes:
        - ./:/home/app
      env_file: 
        - .env
      depends_on:
        - postgres
      entrypoint:
        - npm 
        - run 
        - ${NODE_ENV}
      ports:
        - "${PORT}:3000"
        - "${DEBUG_PORT}:9229"

    postgres:
      container_name: myfas-api-postgres
      image: postgres:12
      hostname: ${DB_HOST}
      environment:
        POSTGRES_DB: ${DB_NAME}
        PGPORT: ${DB_PORT}
        PGDATA: "/var/lib/postgresql/data"
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}

